-- =====================================================================
-- MécaTrack - V1 : création du schéma (7 tables issues du MLD)
-- Clés primaires par identité Oracle, contraintes nommées :
--   PK_ clé primaire, FK_ clé étrangère, UK_ unicité, CK_ vérification
-- Les index de performance seront ajoutés au Sprint 4 (UC-DB3),
-- après mesure avec EXPLAIN PLAN.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ZONE
-- ---------------------------------------------------------------------
CREATE TABLE zone (
    id_zone     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code        VARCHAR2(10)  NOT NULL,
    libelle     VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_zone PRIMARY KEY (id_zone),
    CONSTRAINT uk_zone_code UNIQUE (code)
);

-- ---------------------------------------------------------------------
-- TYPE_EQUIPEMENT
-- ---------------------------------------------------------------------
CREATE TABLE type_equipement (
    id_type     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    libelle     VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_type_equipement PRIMARY KEY (id_type),
    CONSTRAINT uk_type_equipement_libelle UNIQUE (libelle)
);

-- ---------------------------------------------------------------------
-- UTILISATEUR
-- ---------------------------------------------------------------------
CREATE TABLE utilisateur (
    id_utilisateur     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nom                VARCHAR2(50)  NOT NULL,
    prenom             VARCHAR2(50)  NOT NULL,
    email              VARCHAR2(255) NOT NULL,
    mot_de_passe_hash  VARCHAR2(100) NOT NULL,
    role               VARCHAR2(20)  NOT NULL,
    actif              BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT pk_utilisateur PRIMARY KEY (id_utilisateur),
    CONSTRAINT uk_utilisateur_email UNIQUE (email),
    CONSTRAINT ck_utilisateur_role CHECK (role IN ('DEMANDEUR', 'TECHNICIEN', 'ADMIN'))
);

-- ---------------------------------------------------------------------
-- EQUIPEMENT
-- ---------------------------------------------------------------------
CREATE TABLE equipement (
    id_equipement      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    reference          VARCHAR2(30)  NOT NULL,
    nom                VARCHAR2(100) NOT NULL,
    date_mise_service  DATE          NOT NULL,
    statut             VARCHAR2(20)  DEFAULT 'EN_SERVICE' NOT NULL,
    id_type            NUMBER(10)    NOT NULL,
    id_zone            NUMBER(10)    NOT NULL,
    CONSTRAINT pk_equipement PRIMARY KEY (id_equipement),
    CONSTRAINT uk_equipement_reference UNIQUE (reference),
    CONSTRAINT ck_equipement_statut CHECK (statut IN ('EN_SERVICE', 'EN_PANNE', 'EN_MAINTENANCE', 'ARCHIVE')),
    CONSTRAINT fk_equipement_type FOREIGN KEY (id_type) REFERENCES type_equipement (id_type),
    CONSTRAINT fk_equipement_zone FOREIGN KEY (id_zone) REFERENCES zone (id_zone)
);

-- ---------------------------------------------------------------------
-- HABILITATION (association ETRE_HABILITE du MCD)
-- ---------------------------------------------------------------------
CREATE TABLE habilitation (
    id_type            NUMBER(10) NOT NULL,
    id_technicien      NUMBER(10) NOT NULL,
    date_habilitation  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_habilitation PRIMARY KEY (id_type, id_technicien),
    CONSTRAINT fk_habilitation_type FOREIGN KEY (id_type) REFERENCES type_equipement (id_type),
    CONSTRAINT fk_habilitation_technicien FOREIGN KEY (id_technicien) REFERENCES utilisateur (id_utilisateur)
);

-- ---------------------------------------------------------------------
-- INTERVENTION
-- ---------------------------------------------------------------------
CREATE TABLE intervention (
    id_intervention    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    numero             VARCHAR2(20)   NOT NULL,
    titre              VARCHAR2(100)  NOT NULL,
    description        VARCHAR2(1000) NOT NULL,
    priorite           VARCHAR2(10)   NOT NULL,
    statut             VARCHAR2(20)   DEFAULT 'DEMANDEE' NOT NULL,
    date_demande       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    date_planifiee     TIMESTAMP,
    date_debut         TIMESTAMP,
    date_fin           TIMESTAMP,
    temps_passe_min    NUMBER(6),
    compte_rendu       VARCHAR2(2000),
    motif_annulation   VARCHAR2(500),
    version            NUMBER(10)     DEFAULT 0 NOT NULL,
    id_equipement      NUMBER(10)     NOT NULL,
    id_demandeur       NUMBER(10)     NOT NULL,
    id_technicien      NUMBER(10),
    id_modifie_par     NUMBER(10)     NOT NULL,
    CONSTRAINT pk_intervention PRIMARY KEY (id_intervention),
    CONSTRAINT uk_intervention_numero UNIQUE (numero),
    CONSTRAINT ck_intervention_priorite CHECK (priorite IN ('BASSE', 'NORMALE', 'HAUTE', 'CRITIQUE')),
    CONSTRAINT ck_intervention_statut CHECK (statut IN ('DEMANDEE', 'PLANIFIEE', 'EN_COURS', 'TERMINEE', 'ANNULEE')),
    CONSTRAINT ck_intervention_temps CHECK (temps_passe_min > 0),
    CONSTRAINT ck_intervention_dates CHECK (date_fin IS NULL OR date_debut IS NULL OR date_fin >= date_debut),
    -- RG-03 : une intervention terminée a un compte rendu, une date de fin et un temps passé
    CONSTRAINT ck_intervention_terminee CHECK (
        statut <> 'TERMINEE'
        OR (compte_rendu IS NOT NULL AND date_fin IS NOT NULL AND temps_passe_min IS NOT NULL)
    ),
    -- RG-03 : une intervention annulée a un motif
    CONSTRAINT ck_intervention_annulee CHECK (statut <> 'ANNULEE' OR motif_annulation IS NOT NULL),
    -- Une intervention planifiée ou au-delà a un technicien (sauf si annulée avant planification)
    CONSTRAINT ck_intervention_technicien CHECK (
        statut NOT IN ('PLANIFIEE', 'EN_COURS', 'TERMINEE') OR id_technicien IS NOT NULL
    ),
    CONSTRAINT fk_intervention_equipement FOREIGN KEY (id_equipement) REFERENCES equipement (id_equipement),
    CONSTRAINT fk_intervention_demandeur FOREIGN KEY (id_demandeur) REFERENCES utilisateur (id_utilisateur),
    CONSTRAINT fk_intervention_technicien FOREIGN KEY (id_technicien) REFERENCES utilisateur (id_utilisateur),
    CONSTRAINT fk_intervention_modifie_par FOREIGN KEY (id_modifie_par) REFERENCES utilisateur (id_utilisateur)
);

-- ---------------------------------------------------------------------
-- HISTORIQUE_STATUT (alimentée par trigger au Sprint 4)
-- ---------------------------------------------------------------------
CREATE TABLE historique_statut (
    id_historique      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ancien_statut      VARCHAR2(20),
    nouveau_statut     VARCHAR2(20) NOT NULL,
    date_changement    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    id_intervention    NUMBER(10) NOT NULL,
    id_auteur          NUMBER(10) NOT NULL,
    CONSTRAINT pk_historique_statut PRIMARY KEY (id_historique),
    CONSTRAINT ck_historique_ancien CHECK (
        ancien_statut IS NULL OR ancien_statut IN ('DEMANDEE', 'PLANIFIEE', 'EN_COURS', 'TERMINEE', 'ANNULEE')
    ),
    CONSTRAINT ck_historique_nouveau CHECK (
        nouveau_statut IN ('DEMANDEE', 'PLANIFIEE', 'EN_COURS', 'TERMINEE', 'ANNULEE')
    ),
    CONSTRAINT fk_historique_intervention FOREIGN KEY (id_intervention) REFERENCES intervention (id_intervention),
    CONSTRAINT fk_historique_auteur FOREIGN KEY (id_auteur) REFERENCES utilisateur (id_utilisateur)
);
